### entry point for the script
get http://localhost:3001/

### get all users
get http://localhost:3001/users

### get user by id
get http://localhost:3001/users/621d3abd37b01d44ca43cafc

### post a new user
POST http://localhost:3001/users
Content-Type: application/json

{
  "name": "Juanfri Losa",
  "email": "juanfril@gmail.com",
  "password": "12345678",
  "avatar": "https://avatars2.githubusercontent.com/u/1234?v=3&s=460",
  "whatsapp": "09123456789",
  "bio": "I am a software developer"
}

### update user
PUT http://localhost:3001/users/621d3abd37b01d44ca43cafc
Content-Type: application/json

{
  "name": "Juanfri Losa Marquez",
  "email": "juanfril@gmail.com",
  "password": "12345678",
  "avatar": "https://avatars2.githubusercontent.com/u/1234?v=3&s=460",
  "whatsapp": "666666666",
  "bio": "I'm a software developer"
}

### delete a user
delete http://localhost:3001/users/621d34009a747ce82c7e5a7a